// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFp_ZSuMLebvBKWKQmhMicE6T2qB1MMg',
    appId: '1:602166267311:web:d6670a937abb1ad76df35a',
    messagingSenderId: '602166267311',
    projectId: 'baia-1df5a',
    authDomain: 'baia-1df5a.firebaseapp.com',
    databaseURL: 'https://baia-1df5a-default-rtdb.firebaseio.com',
    storageBucket: 'baia-1df5a.appspot.com',
    measurementId: 'G-HFFZYTEN0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkb4NJ0FQPVF1BID-ykrzhAzT2htmSR24',
    appId: '1:602166267311:android:e89d065506f896e96df35a',
    messagingSenderId: '602166267311',
    projectId: 'baia-1df5a',
    databaseURL: 'https://baia-1df5a-default-rtdb.firebaseio.com',
    storageBucket: 'baia-1df5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1pLVHRwmbyz0kIDHYw346vjZ6Mn3_cQ',
    appId: '1:602166267311:ios:c65b92374e256bd26df35a',
    messagingSenderId: '602166267311',
    projectId: 'baia-1df5a',
    databaseURL: 'https://baia-1df5a-default-rtdb.firebaseio.com',
    storageBucket: 'baia-1df5a.appspot.com',
    iosBundleId: 'com.example.baiaUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG1pLVHRwmbyz0kIDHYw346vjZ6Mn3_cQ',
    appId: '1:602166267311:ios:c65b92374e256bd26df35a',
    messagingSenderId: '602166267311',
    projectId: 'baia-1df5a',
    databaseURL: 'https://baia-1df5a-default-rtdb.firebaseio.com',
    storageBucket: 'baia-1df5a.appspot.com',
    iosBundleId: 'com.example.baiaUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFp_ZSuMLebvBKWKQmhMicE6T2qB1MMg',
    appId: '1:602166267311:web:1071dbca562a91ba6df35a',
    messagingSenderId: '602166267311',
    projectId: 'baia-1df5a',
    authDomain: 'baia-1df5a.firebaseapp.com',
    databaseURL: 'https://baia-1df5a-default-rtdb.firebaseio.com',
    storageBucket: 'baia-1df5a.appspot.com',
    measurementId: 'G-06G6W8G3J6',
  );
}
